[DEBUG]
log_level = 10

[MONGODB]
uri = 'mongodb://localhost:27017'
database = 'demo'
max_pool_size = 5
min_pool_size = 0

[ORIGIN]
allowed = ['*']

[secrets]
SECRET_KEY = ""

[auth]
ACCESS_TOKEN_EXPIRE_MINUTES = 30

[OPENAI]
api_key = ""

[ELASTICSEARCH]
host = 'http://localhost:9200'
